version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - doc
            - aiida
            - crystal_structure_generation
            - phonos
            - database_interfaces
            - graphs
            - ml
            - plots

# Let the build fail if there are any warnings
sphinx:
    builder: html
    fail_on_warning: false
